apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: server1
            clusterServer: https://192.168.1.200:6443
          - cluster: server2
            clusterServer: https://192.168.1.201:6443
          - cluster: server3
            clusterServer: https://kubernetes.default.svc
  template:
    metadata:
      name: external-dns-{{cluster}}
    spec:
      project: default
      sources:
        - repoURL: https://kubernetes-sigs.github.io/external-dns/
          chart: external-dns
          targetRevision: 1.20.0
          helm:
            releaseName: external-dns
            valueFiles:
              - $values/gitops/helm-values/external-dns.yaml
              - $values/gitops/helm-values/{{cluster}}/external-dns.yaml
        - repoURL: https://github.com/radoslavirha/homelab
          targetRevision: HEAD
          ref: values
        - repoURL: https://github.com/radoslavirha/homelab
          targetRevision: HEAD
          path: gitops/k8s-manifests/{{cluster}}/external-dns
      destination:
        server: '{{clusterServer}}'
        namespace: external-dns
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
