---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-prometheus
  namespace: monitoring
  labels:
    grafana_datasource: "1"
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
data:
  datasource-prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus.monitoring.svc.cluster.local
        isDefault: true
        editable: false
        jsonData:
          httpMethod: POST
