---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-server2.influxdb2
  namespace: monitoring
  labels:
    grafana_datasource: "1"
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
data:
  datasource-influxdb2.yaml: |-
    apiVersion: 1
    datasources:
      - name: InfluxDB2 Server2
        type: influxdb
        uid: influxdb2-server2
        access: proxy
        url: http://influx.server2.home
        editable: false
        jsonData:
          version: Flux
          organization: homelab
          defaultBucket: loxone
          tlsSkipVerify: true
        secureJsonData:
          token: $__file{/etc/secrets/server2-influxdb2-grafana/token}
