---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdb2-grafana
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: influxdb2-grafana
  data:
    - secretKey: token
      remoteRef:
        key: server3/influxdb2-grafana
        property: token
