# cluster VARs
# Shared across all apps deployed on cluster.
VAR_PROTOCOL: http
VAR_MQTT_URL: "mqtt://emqx.iot.svc.cluster.local:1883"
VAR_MONGODB_URL: "mongodb://mongodb.mongodb.svc.cluster.local:27017"