apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-ui-server3
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/radoslavirha/homelab
      targetRevision: HEAD
      path: gitops/k8s-manifests/server3/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
