# ── Server3 cluster — vault-config ─────────────────────────────────────────
# OpenBao's own configuration: auth methods, policies, identity groups. Today that is OIDC
# login via Authentik, plus the Kubernetes auth roles the provisioner Jobs log in with.
#
# Runs LAST on a fresh server3: after GitOps bootstrap, once authentik-server3 is Healthy and the
# blueprint has created the openbao-server3-production provider. The OIDC client secret is
# generated by Authentik, so nothing in this stage can run earlier. Anything added later that must
# exist before the FIRST ArgoCD Application carrying an ExternalSecret (ESO's own Kubernetes auth
# mount, for example) needs its own toggle or its own stage — authentik itself has ExternalSecrets,
# so ESO already has to work before this stage can run at all. Note that is not "before ArgoCD":
# ArgoCD installs with no ESO, its secret coming straight from OpenBao via modules/apps/argocd.tf.
#
# Prerequisites:
#   1. An admin OpenBao session: userpass or root, never oidc, which is what this stage creates.
#        export VAULT_ADDR=https://vault.server3.homelab.irha.cz   # or port-forward + http://127.0.0.1:8200
#        bao login -method=userpass username=<admin>              # writes ~/.vault-token
#        export VAULT_TOKEN=$(cat ~/.vault-token)
#   2. The client secret in KV, copied from Authentik → Applications → Providers →
#      openbao-server3-production → Edit → Client Secret:
#        read -rs S && bao kv put secret/server3/openbao oidc-client-secret="$S"; unset S
#
# Usage:
#   cd iac/clusters/server3/vault-config
#   terraform init && terraform plan && terraform apply

terraform {
  required_version = ">= 1.11.0"

  # Same chicken-and-egg situation as bootstrap — local state until MinIO is live.
  # backend "s3" { ... key = "clusters/server3/vault-config/terraform.tfstate" ... }
}

provider "vault" {
  # Reads VAULT_ADDR and VAULT_TOKEN from environment.
  # No address hardcoded — set before running terraform apply.
}

module "vault_config" {
  source = "../../../modules/vault-config"

  # ── OIDC login via Authentik ───────────────────────────────────────────────
  # Authentik side: the `openbao` entry in gitops/helm-values/server3/authentik-blueprints.yaml.
  oidc_discovery_url      = "https://auth.irha.cz/application/o/openbao-server3-production/"
  oidc_client_id          = "openbao-server3-production"
  oidc_client_secret_path = "server3/openbao"
  # Bump after putting a regenerated secret into KV. Write-only values are never read back,
  # so this number is the only way Terraform learns that the secret changed.
  oidc_client_secret_version = 1

  # Only the UI callback. The CLI's http://localhost:8250/oidc/callback is deliberately absent:
  # a loopback URI on a production client is what Authentik's `local` environments exist to avoid.
  oidc_redirect_uris = [
    "https://vault.server3.homelab.irha.cz/ui/vault/auth/oidc/oidc/callback",
  ]

  # ── Kubernetes auth — provisioner roles ────────────────────────────────────
  # Keys are auth MOUNT paths created by the CLI (docs/iac.md § 3.c); only the role is managed
  # here. See modules/vault-config/kubernetes.tf for why the mount and ESO's role are not.
  # Namespaces are where the provisioner chart renders its PostSync Jobs: EMQX and InfluxDB2
  # into `iot`, MongoDB into `mongodb`. server2 and server3 run no provisioner Jobs.
  kubernetes_provisioner_roles = {
    "kubernetes-server1" = {
      namespaces     = ["iot", "mongodb"]
      token_policies = ["server1-provisioner"]
    }
  }

  # Keys are `roles` claim values from the Authentik ladder (docs/identity.md). An admin's token
  # carries all three, so an admin holds all three policies.
  oidc_groups = {
    "openbao.admin" = {
      policy_name = "oidc-admin"
      policy      = file("${path.root}/policies/oidc-admin.hcl")
    }
    "openbao.editor" = {
      policy_name = "oidc-editor"
      policy      = file("${path.root}/policies/oidc-editor.hcl")
    }
    "openbao.reader" = {
      policy_name = "oidc-reader"
      policy      = file("${path.root}/policies/oidc-reader.hcl")
    }
  }
}
