{{- $applicationName := .Release.Name -}}
{{- $application := .Values -}}
{{- include "app.validators.image" (dict "image" $application.image "applicationName" $applicationName) }}
{{- include "app.validators.services" (dict "services" ($application.services | default dict) "applicationName" $applicationName) }}
{{- $ctx := dict "application" $application "name" $applicationName "release" $.Release "chart" $.Chart -}}
{{- range $serviceName, $svc := $application.services | default dict }}
{{- if $svc.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.identifier" $ctx }}-{{ $serviceName }}
  labels: {{ include "app.meta.labels" $ctx | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{ include "app.labels.selector" $ctx | nindent 4 }}
  ports:
    - name: {{ $serviceName }}
      protocol: {{ $svc.protocol | default "TCP" }}
      port: {{ $svc.port | default 80 }}
      targetPort: {{ $svc.targetPort | default 80 }}
{{ end }}
{{ end }}
