{{- range $applicationName, $application := .Values.apps | default dict -}}
{{- include "iot-applications.validators.ingress" (dict "ingress" $application.ingress "applicationName" $applicationName) }}
{{- if $application.ingress.enabled }}
{{- $ctx := dict "application" $application "name" $applicationName "release" $.Release "chart" $.Chart -}}
{{- $pathName := $application.ingress.pathName | default $applicationName -}}
{{- $stripPrefix := dig "stripPrefix" true ($application.ingress | default dict) -}}
{{- if $stripPrefix }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "iot-applications.identifier" $ctx }}-middleware-stripprefix
  labels: {{ include "iot-applications.meta.labels" $ctx | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /{{ $pathName }}
{{- end }}
{{ end }}
{{ end }}