# qr-manager-ui — production overrides

apps:
  qr-manager-ui:
    image:
      tag: "0.4.0"
    templates:
      config:
        content: |
          {
              "apiBaseURL": "{{ VAR_PROTOCOL }}://api.{{ VAR_PUBLIC_DOMAIN }}/iot/qr-manager",
              "basePath": "/qr-manager"
          }
