# Bare A record for server2.home → 192.168.1.201
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: server2-home
  namespace: external-dns
spec:
  endpoints:
    - dnsName: server2.home
      recordType: A
      recordTTL: 180
      targets:
        - 192.168.1.201
