{{- /*
Login surface hardening. Rendered into its own ConfigMap key by configmap.yaml.

Everything here is about one question: what happens when this login page is
reachable from the internet rather than only from 192.168.1.0/24.
*/ -}}
{{- define "authentik-blueprints.hardening" -}}
# GENERATED by gitops/helm-charts/authentik-blueprints. Do not edit here --
# edit gitops/helm-values/server3/authentik-blueprints.yaml.
version: 1
metadata:
  name: homelab - login surface hardening
entries:

  # ---------- anti-enumeration ----------
  # UPDATED, not created: the only field this intends to change on the shipped
  # identification stage is show_matched_user. user_fields is repeated below for a
  # validation reason, not because it changes -- see the comment on it.
  #
  # show_matched_user renders the matched account's name and avatar once a username
  # is entered -- a free "does this account exist?" oracle for anyone who reaches the
  # page. Harmless on a LAN-only host, not harmless when published.
  #
  # The recovery flow is deliberately NOT named here. The onboarding work left it
  # unset so the login page shows no "Forgot password?", which is what keeps a reset
  # form off the public page; recovery is an admin-minted link via the brand.
  - model: authentik_stages_identification.identificationstage
    identifiers:
      name: default-authentication-identification
    attrs:
      show_matched_user: false
      # user_fields is NOT a field we want to change -- it is repeated here because
      # the entry does not validate without it.
      #
      # The importer updates by identifiers with partial=True, so unmentioned fields
      # keep their stored values on SAVE. Validation is a different matter:
      # IdentificationStageSerializer.validate() does
      #     user_fields = attrs.get("user_fields", [])
      #     if len(user_fields) < 1 and len(sources) < 1: raise
      # and under a partial update `attrs` holds only what the entry supplied. So an
      # entry naming show_matched_user alone reads as "no user fields, no sources"
      # and is rejected with "When no user fields are selected, at least one source
      # must be selected" -- at import time, an hour later, in a worker log.
      #
      # Measured on server3 2026-09-21; keep in step with the running stage.
      user_fields:
        - email
        - username

  # ---------- brute-force throttling ----------
  # The score itself needs no configuration: Authentik writes it on every login
  # outcome. What this builds is the consequence.
  - model: authentik_policies_reputation.reputationpolicy
    id: policy-reputation-login
    identifiers:
      name: homelab-reputation-login
    attrs:
      check_ip: {{ .Values.hardening.reputation.checkIp }}
      check_username: {{ .Values.hardening.reputation.checkUsername }}
      threshold: {{ .Values.hardening.reputation.threshold }}

  # A deny stage is how a policy becomes a refusal. The policy is bound to THIS
  # stage's binding below: when the score is bad the policy passes, the stage runs,
  # and the flow ends here.
  - model: authentik_stages_deny.denystage
    id: stage-reputation-deny
    identifiers:
      name: homelab-reputation-deny
    attrs:
      deny_message: Too many failed attempts. Try again later.

  # order 15 -- after identification (10), before password (20). The username is in
  # the flow context by then, which is what a username-keyed score needs. Measured
  # on server3: the shipped flow binds 10, 20, 30 and 100, so 15 is free.
  - model: authentik_flows.flowstagebinding
    id: binding-reputation-deny
    identifiers:
      target: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
      stage: !KeyOf stage-reputation-deny
      order: 15
    attrs:
      # Evaluate when the stage RUNS, not when the flow is planned: a plan-time
      # evaluation reads the score from before the current attempt.
      evaluate_on_plan: false
      re_evaluate_policies: true

  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf binding-reputation-deny
      policy: !KeyOf policy-reputation-login
      order: 0
    attrs:
      enabled: true
      timeout: 30

  # ---------- MFA ----------
  # No stages are created here. Authentik ships default-authenticator-{webauthn,totp,
  # static}-setup, each with a configure_flow -- which is what makes a stage reachable
  # from user settings. A copy made by this chart would have none, so enrolment outside
  # the login flow would silently have nothing to offer.
  #
  # UPDATED, not created: the shipped validation stage is already bound into the
  # authentication flow at order 30. Only these three fields move.
  - model: authentik_stages_authenticator_validate.authenticatorvalidatestage
    identifiers:
      name: default-authentication-mfa-validation
    attrs:
      device_classes:
{{- range .Values.hardening.mfa.deviceClasses }}
        - {{ . }}
{{- end }}
      not_configured_action: {{ .Values.hardening.mfa.notConfiguredAction }}
      # The enrolment chooser. TWO entries on purpose: authentik auto-selects a
      # single one without showing a choice, and refuses the login outright when the
      # list is empty. Passkey first on Apple hardware is Face ID or Touch ID with the
      # credential in iCloud Keychain; TOTP is the answer for a device without a
      # platform authenticator.
      #
      # Static setup is NOT here -- see deviceClasses in values.yaml.
      configuration_stages:
        - !Find [authentik_stages_authenticator_webauthn.authenticatorwebauthnstage, [name, default-authenticator-webauthn-setup]]
        - !Find [authentik_stages_authenticator_totp.authenticatortotpstage, [name, default-authenticator-totp-setup]]
{{- end -}}
