{{- /*
Login surface hardening. Rendered into its own ConfigMap key by configmap.yaml.

Everything here is about one question: what happens when this login page is
reachable from the internet rather than only from 192.168.1.0/24.
*/ -}}
{{- define "authentik-blueprints.hardening" -}}
# GENERATED by gitops/helm-charts/authentik-blueprints. Do not edit here --
# edit gitops/helm-values/server3/authentik-blueprints.yaml.
version: 1
metadata:
  name: homelab - login surface hardening
entries:

  # ---------- anti-enumeration ----------
  # UPDATED, not created: the only field this intends to change on the shipped
  # identification stage is show_matched_user. user_fields is repeated below for a
  # validation reason, not because it changes -- see the comment on it.
  #
  # show_matched_user renders the matched account's name and avatar once a username
  # is entered -- a free "does this account exist?" oracle for anyone who reaches the
  # page. Harmless on a LAN-only host, not harmless when published.
  #
  # The recovery flow is deliberately NOT named here. The onboarding work left it
  # unset so the login page shows no "Forgot password?", which is what keeps a reset
  # form off the public page; recovery is an admin-minted link via the brand.
  - model: authentik_stages_identification.identificationstage
    identifiers:
      name: default-authentication-identification
    attrs:
      show_matched_user: false
      # user_fields is NOT a field we want to change -- it is repeated here because
      # the entry does not validate without it.
      #
      # The importer updates by identifiers with partial=True, so unmentioned fields
      # keep their stored values on SAVE. Validation is a different matter:
      # IdentificationStageSerializer.validate() does
      #     user_fields = attrs.get("user_fields", [])
      #     if len(user_fields) < 1 and len(sources) < 1: raise
      # and under a partial update `attrs` holds only what the entry supplied. So an
      # entry naming show_matched_user alone reads as "no user fields, no sources"
      # and is rejected with "When no user fields are selected, at least one source
      # must be selected" -- at import time, an hour later, in a worker log.
      #
      # Measured on server3 2026-09-21; keep in step with the running stage.
      user_fields:
        - email
        - username
{{- end -}}
