{{- /*
Onboarding blueprint: invitation-gated enrollment, and recovery by admin-minted link.

Rendered into its OWN ConfigMap key (homelab-onboarding.yaml). Authentik discovers
each .yaml key as a separate blueprint FILE and gives each its own BlueprintInstance,
so a malformed entry here cannot take homelab-applications.yaml down with it. The
cost is that !KeyOf cannot cross the two files — nothing here needs to.

Shape follows authentik's own /blueprints/example/flows-invitation-enrollment.yaml,
which ships inert (blueprints.goauthentik.io/instantiate: "false").

INVARIANT: the invitation stage is bound FIRST, with
continue_flow_without_invitation: false. That is what makes this flow's URL safe to
be internet-reachable: no token, no account, nothing disclosed.

INVARIANT: the prompt stage renders NO username field. The username comes from the
invitation's fixed_data, which the invitation stage merges into prompt_data
(always_merger.merge, authentik/stages/invitation/stage.py) — and a rendered field
would overwrite it with whatever the invitee typed.

Design: docs/superpowers/specs/2026-09-18-authentik-identity-hardening.md
*/ -}}
{{- define "authentik-blueprints.onboarding" -}}
# GENERATED by gitops/helm-charts/authentik-blueprints. Do not edit here —
# edit the onboarding block in gitops/helm-values/server3/authentik-blueprints.yaml.
version: 1
metadata:
  name: homelab - onboarding
entries:

  # ---------- the group invited members land in ----------
  # Grants NOTHING on its own: no application binding, no ladder parentage. It
  # exists so "who came in by invitation" is one query, and so a future
  # household-wide application has a single object to bind.
  - model: authentik_core.group
    id: grp-household
    identifiers:
      name: {{ .Values.onboarding.group }}
    attrs:
      is_superuser: false

  # ---------- enrollment ----------
  - model: authentik_flows.flow
    id: flow-enrollment
    identifiers:
      slug: homelab-enrollment
    attrs:
      name: homelab-enrollment
      title: {{ .Values.onboarding.enrollmentTitle | quote }}
      designation: enrollment
      authentication: require_unauthenticated

  # THE GATE. Without a valid ?itoken=, the flow dead-ends here.
  - model: authentik_stages_invitation.invitationstage
    id: stage-enrollment-invitation
    identifiers:
      name: homelab-enrollment-invitation
    attrs:
      continue_flow_without_invitation: false

  - model: authentik_stages_prompt.prompt
    id: prompt-enrollment-name
    identifiers:
      name: homelab-enrollment-field-name
    attrs:
      field_key: name
      label: Name
      type: text
      required: true
      placeholder: Name
      placeholder_expression: false
      order: 0

  # The invitee owns their own email: nothing matches accounts on it (Mealie moved
  # to preferred_username), so a wrong value costs a wrong address on a profile.
  - model: authentik_stages_prompt.prompt
    id: prompt-enrollment-email
    identifiers:
      name: homelab-enrollment-field-email
    attrs:
      field_key: email
      label: Email
      type: email
      required: true
      placeholder: Email
      placeholder_expression: false
      order: 1

  # EXACTLY TWO password fields. PromptChallengeResponse.validate compares them
  # only when the stage holds two; a third silently disables the match check.
  - model: authentik_stages_prompt.prompt
    id: prompt-enrollment-password
    identifiers:
      name: homelab-enrollment-field-password
    attrs:
      field_key: password
      label: Password
      type: password
      required: true
      placeholder: Password
      placeholder_expression: false
      order: 2

  - model: authentik_stages_prompt.prompt
    id: prompt-enrollment-password-repeat
    identifiers:
      name: homelab-enrollment-field-password-repeat
    attrs:
      field_key: password_repeat
      label: Password (repeat)
      type: password
      required: true
      placeholder: Password (repeat)
      placeholder_expression: false
      order: 3

  - model: authentik_stages_prompt.promptstage
    id: stage-enrollment-prompt
    identifiers:
      name: homelab-enrollment-prompt
    attrs:
      fields:
        - !KeyOf prompt-enrollment-name
        - !KeyOf prompt-enrollment-email
        - !KeyOf prompt-enrollment-password
        - !KeyOf prompt-enrollment-password-repeat
      # authentik's shipped password policy, reused rather than a second one:
      # length_min 8 plus charset rules, and it validates the field named
      # `password`, which is what the prompt above calls it.
      validation_policies:
        - !Find [authentik_policies_password.passwordpolicy, [name, default-password-change-password-policy]]

  - model: authentik_stages_user_write.userwritestage
    id: stage-enrollment-write
    identifiers:
      name: homelab-enrollment-write
    attrs:
      user_creation_mode: always_create
      create_users_as_inactive: false
      create_users_group: !KeyOf grp-household
      user_type: internal
      user_path_template: {{ .Values.onboarding.userPath }}

  - model: authentik_stages_user_login.userloginstage
    id: stage-enrollment-login
    identifiers:
      name: homelab-enrollment-login

  - model: authentik_flows.flowstagebinding
    identifiers:
      target: !KeyOf flow-enrollment
      stage: !KeyOf stage-enrollment-invitation
      order: 10
    attrs:
      evaluate_on_plan: true
      re_evaluate_policies: true

  - model: authentik_flows.flowstagebinding
    identifiers:
      target: !KeyOf flow-enrollment
      stage: !KeyOf stage-enrollment-prompt
      order: 20

  - model: authentik_flows.flowstagebinding
    identifiers:
      target: !KeyOf flow-enrollment
      stage: !KeyOf stage-enrollment-write
      order: 30

  - model: authentik_flows.flowstagebinding
    identifiers:
      target: !KeyOf flow-enrollment
      stage: !KeyOf stage-enrollment-login
      order: 100

  # ---------- recovery ----------
  # Reached ONLY from an admin-minted link (Directory -> Users -> Create recovery
  # link), which is why brand.flow_recovery is set below while the identification
  # stage's own recovery_flow is deliberately left alone: the public login page
  # shows no "Forgot password?", so there is no reset form to enumerate usernames
  # with, and no SMTP is needed to run it.
  #
  # The cost is that the operator IS the recovery path. SMTP is the documented
  # upgrade, not a redesign -- see the spec's "SMTP: deferred, not rejected".
  - model: authentik_flows.flow
    id: flow-recovery
    identifiers:
      slug: homelab-recovery
    attrs:
      name: homelab-recovery
      title: {{ .Values.onboarding.recoveryTitle | quote }}
      designation: recovery
      authentication: require_unauthenticated

  - model: authentik_stages_prompt.prompt
    id: prompt-recovery-password
    identifiers:
      name: homelab-recovery-field-password
    attrs:
      field_key: password
      label: Password
      type: password
      required: true
      placeholder: Password
      placeholder_expression: false
      order: 0

  - model: authentik_stages_prompt.prompt
    id: prompt-recovery-password-repeat
    identifiers:
      name: homelab-recovery-field-password-repeat
    attrs:
      field_key: password_repeat
      label: Password (repeat)
      type: password
      required: true
      placeholder: Password (repeat)
      placeholder_expression: false
      order: 1

  - model: authentik_stages_prompt.promptstage
    id: stage-recovery-prompt
    identifiers:
      name: homelab-recovery-prompt
    attrs:
      fields:
        - !KeyOf prompt-recovery-password
        - !KeyOf prompt-recovery-password-repeat
      validation_policies:
        - !Find [authentik_policies_password.passwordpolicy, [name, default-password-change-password-policy]]

  # never_create: a recovery link names its user. This stage must never mint one.
  - model: authentik_stages_user_write.userwritestage
    id: stage-recovery-write
    identifiers:
      name: homelab-recovery-write
    attrs:
      user_creation_mode: never_create

  - model: authentik_flows.flowstagebinding
    identifiers:
      target: !KeyOf flow-recovery
      stage: !KeyOf stage-recovery-prompt
      order: 10

  - model: authentik_flows.flowstagebinding
    identifiers:
      target: !KeyOf flow-recovery
      stage: !KeyOf stage-recovery-write
      order: 20

  # UPDATED, not created: a blueprint leaves unmentioned fields exactly as it
  # found them, so only flow_recovery changes on the default brand.
  - model: authentik_brands.brand
    identifiers:
      domain: authentik-default
    attrs:
      flow_recovery: !KeyOf flow-recovery
{{- end -}}
