# ── OIDC login via Authentik ─────────────────────────────────────────────────
# Authentik side: the `openbao` entry in gitops/helm-values/server3/authentik-blueprints.yaml.
# It is a confidential client because OpenBao refuses an oidc_client_id without a secret, and
# that secret is GENERATED by Authentik. It therefore cannot exist before GitOps has deployed
# Authentik and the blueprint has landed, which is why this stage runs last on a fresh server3.
#
# userpass and the root token are NOT managed here and must stay. Authentik's own secrets come
# from OpenBao, so OpenBao must never need Authentik in order to be administered.

# Ephemeral, not a data source: the value is used for this run only and never written to state.
ephemeral "vault_kv_secret_v2" "oidc_client_secret" {
  mount = "secret"
  name  = var.oidc_client_secret_path
}

resource "vault_jwt_auth_backend" "oidc" {
  path        = var.oidc_mount_path
  type        = "oidc"
  description = "Human login via Authentik (auth.irha.cz)"

  oidc_discovery_url = var.oidc_discovery_url
  oidc_client_id     = var.oidc_client_id
  # Write-only: sent to OpenBao, never stored in state, never read back. Terraform cannot see
  # drift in it, so a rotated secret reaches OpenBao only when oidc_client_secret_version moves.
  oidc_client_secret_wo         = tostring(ephemeral.vault_kv_secret_v2.oidc_client_secret.data["oidc-client-secret"])
  oidc_client_secret_wo_version = var.oidc_client_secret_version
  default_role                  = var.oidc_role_name

  tune {
    # Lists "OIDC" among the login page's methods. Without it the method works but is hidden.
    listing_visibility = "unauth"
  }
}

resource "vault_jwt_auth_backend_role" "oidc" {
  backend   = vault_jwt_auth_backend.oidc.path
  role_name = var.oidc_role_name
  role_type = "oidc"

  # `sub` is the Authentik username (sub_mode: user_username), which becomes the entity alias.
  user_claim = "sub"
  # Already filtered to this application and flattened by the role ladder: an admin's token
  # carries ["openbao.admin", "openbao.editor", "openbao.reader"]. Each value is matched against
  # the group aliases below, so an admin gets all three policies with no ordering logic here.
  groups_claim = "roles"
  # OpenBao adds `openid` itself. `roles` is NOT implied by `profile`: leave it out and every
  # login still succeeds, with no groups, and therefore with only the default policy.
  oidc_scopes           = ["profile", "email", "roles"]
  bound_audiences       = [var.oidc_client_id]
  allowed_redirect_uris = var.oidc_redirect_uris

  # Privileges come from the external groups, not from the role.
  token_policies = ["default"]
  token_ttl      = var.oidc_token_ttl
  token_max_ttl  = var.oidc_token_max_ttl
}

resource "vault_policy" "oidc" {
  for_each = var.oidc_groups

  name   = each.value.policy_name
  policy = each.value.policy
}

resource "vault_identity_group" "oidc" {
  for_each = var.oidc_groups

  name     = each.key
  type     = "external"
  policies = [vault_policy.oidc[each.key].name]
}

resource "vault_identity_group_alias" "oidc" {
  for_each = var.oidc_groups

  # Must equal the claim value exactly. OpenBao matches groups_claim entries against alias names
  # on this mount, and a mismatch fails silently: the login works and carries no group.
  name           = each.key
  mount_accessor = vault_jwt_auth_backend.oidc.accessor
  canonical_id   = vault_identity_group.oidc[each.key].id
}
