# ── OIDC login via Authentik ─────────────────────────────────────────────────
variable "oidc_mount_path" {
  type        = string
  description = "Auth mount path. The UI callback embeds it (/ui/vault/auth/<path>/oidc/callback), so changing it also means changing oidc_redirect_uris and the Authentik blueprint's redirectPath."
  default     = "oidc"
}

variable "oidc_discovery_url" {
  type        = string
  description = "Authentik's per-provider issuer, e.g. https://auth.irha.cz/application/o/openbao-server3-production/"
}

variable "oidc_client_id" {
  type        = string
  description = "Authentik client_id (<app>-<cluster>-<stage>). Also bound as the required audience."
}

# The client secret is generated by Authentik, so it cannot be declared here. Copy it once into
# KV: bao kv put secret/server3/openbao oidc-client-secret=<value>
variable "oidc_client_secret_path" {
  type        = string
  description = "OpenBao KV v2 path (mount=secret) holding the Authentik-generated client secret under the key oidc-client-secret, e.g. server3/openbao."
}

variable "oidc_client_secret_version" {
  type        = number
  description = "Version counter for the write-only client secret. OpenBao never returns it and Terraform never stores it, so a changed secret is invisible to plan: bump this after rotating the value in KV."
}

variable "oidc_redirect_uris" {
  type        = list(string)
  description = "Allowed redirect URIs. Must match the Authentik provider's registered URIs exactly (strict matching)."
}

variable "oidc_role_name" {
  type        = string
  description = "Name of the single OIDC role, also set as the mount's default_role so the UI login needs no role typed in."
  default     = "authentik"
}

variable "oidc_token_ttl" {
  type        = number
  description = "Default TTL of an OpenBao token issued by an OIDC login, in seconds."
  default     = 3600
}

variable "oidc_token_max_ttl" {
  type        = number
  description = "Maximum TTL of an OpenBao token issued by an OIDC login, in seconds."
  default     = 28800
}

variable "oidc_groups" {
  type = map(object({
    policy_name = string
    policy      = string
  }))
  description = "Keyed by a `roles` claim value (e.g. openbao.admin). Each entry becomes an ACL policy, an external identity group named after the claim, and a group alias on the OIDC mount. Pass policy content with file() in the cluster instance."
}
