apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: emqx
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: server1
            clusterServer: https://192.168.1.200:6443
          - cluster: server2
            clusterServer: https://192.168.1.201:6443
  template:
    metadata:
      name: emqx-{{cluster}}
    spec:
      project: default
      sources:
        - repoURL: https://repos.emqx.io/charts
          chart: emqx
          targetRevision: 5.8.9
          helm:
            releaseName: emqx
            valueFiles:
              - $values/gitops/helm-values/emqx.yaml
              - $values/gitops/helm-values/{{cluster}}/emqx.yaml
        - repoURL: https://github.com/radoslavirha/homelab
          targetRevision: HEAD
          ref: values
        - repoURL: https://github.com/radoslavirha/homelab
          targetRevision: HEAD
          path: gitops/k8s-manifests/{{cluster}}/emqx
        - repoURL: https://github.com/radoslavirha/homelab
          targetRevision: HEAD
          path: gitops/helm-charts/provisioner
          helm:
            releaseName: emqx-provisioner
            valueFiles:
              - $values/gitops/helm-values/{{cluster}}/provisioner/emqx.yaml
      destination:
        server: '{{clusterServer}}'
        namespace: iot
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
