apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: server1
            clusterServer: https://192.168.1.200:6443
          - cluster: server2
            clusterServer: https://192.168.1.201:6443
          - cluster: server3
            clusterServer: https://kubernetes.default.svc
  template:
    metadata:
      name: external-secrets-{{cluster}}
    spec:
      project: default
      sources:
        - repoURL: https://charts.external-secrets.io
          chart: external-secrets
          targetRevision: 2.3.0
          helm:
            releaseName: external-secrets
            valueFiles:
              - $values/gitops/helm-values/external-secrets.yaml
              - $values/gitops/helm-values/{{cluster}}/external-secrets.yaml
        - repoURL: https://github.com/radoslavirha/homelab
          targetRevision: HEAD
          ref: values
        - repoURL: https://github.com/radoslavirha/homelab
          targetRevision: HEAD
          path: gitops/k8s-manifests/{{cluster}}/external-secrets
      destination:
        server: '{{clusterServer}}'
        namespace: external-secrets
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        automated:
          selfHeal: true
          prune: true
